# Generated by Django 4.2.5 on 2023-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0002_remove_video_created_at_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/'),
        ),
    ]
