# Generated by Django 4.2.5 on 2023-09-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0003_video_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='transcription',
        ),
    ]
