# Generated by Django 4.2.5 on 2023-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0004_remove_video_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
