# Generated by Django 4.2.5 on 2023-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0006_remove_video_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
